### PR TITLE
Added Webpack federation support

### PR DESCRIPTION
**Pull request by litong-n99**
Hi there, your plugin awesome. But when I was developing a Monorepo project that both main and sub project need change theme, it will only change the sub project theme. I think the problem is you set '__theme_COLOR_cfg' to Window and sub project overrode it, so main project read incorrect value.
I had added a random number to fix it, and you could have a test by https://github.com/litong-n99/vue2-admin

### CODE REVIEW

**Comment by litong-n99** [comment]
It's already been a week and I haven't gotten a response. This is now becoming urgent for my project.

Could u merge it if it's available or give me a feedback~ @hzsrc

**Comment by hzsrc** [comment]
Normally, you just need to add this plugin into the top project, and do not add to any sub projects. Because if you do this, css will be scaned twice and down load twice, it's not D.
Another reason is, these change may make the plugin code more complicated.
So, I'm afraid that I can't merge this yet.

**Comment by litong-n99** [comment]
I know what you are concerning, and I am sorry about my inaccurate description.

Actually it is a project with **Webpack's federation**, and when main project change theme, the sub project couldn't get the right Theme path.

As you said, I can just add this plugin into the top Monorepo project, but this only applies to the use of **NPM‘s association**, not **Webpack's federation association**.
 
image

**Comment by hzsrc** [comment]
Done this. Thank you!

**Pull request merged**
